### ISSUE TITLE
Bug with wrong authlib.php url on Darwin

### ISSUE THREAD

**Issue by cstones** [pitbulk/moodle-onelogin#1]
Darwin has win in it. So this code uses the wrong url for Mac OS X.
(PHP_OS returns Darwin etc)
```
	if (stristr(strtolower(PHP_OS), "win") === false) {
		require_once($CFG->libdir.'/authlib.php');
	} else {
		require_once($CFG->libdir.'\authlib.php');
	}
```
A quick replacement addresses the issue..
```
$phpos = strtolower(PHP_OS);
if (stristr($phpos, "win") === false or "darwin" === $phpos)
{ require_once($CFG->libdir.'/authlib.php'); }

else
{ require_once($CFG->libdir.'\authlib.php'); } 
```

**Comment by pitbulk** [comment]
Thanks for report that. I will use this code that appears in [different places on moodle](https://github.com/moodle/moodle/blob/803f565753bd9fe41acc802774adac75c2219880/lib/setup.php#L694):

if (stristr($phpos, 'win') && !stristr(PHP_OS, 'darwin')) {
    require_once($CFG->libdir.'/authlib.php');
} else {
    require_once($CFG->libdir.'\authlib.php');
}
